# global config
global:
  scrape_interval:     120s # By default, scrape targets every 15 seconds.
  evaluation_interval: 120s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #  monitor: ''

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
# - "alert.rules"
# - "first.rules"
# - "second.rules"

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 15s
  static_configs:
  - targets: ['localhost:9090','192.168.1.1:9100']
- job_name: 'process-exporter'
  scrape_interval: 15s
  static_configs:
  - targets: ['process-exporter:9256']
- job_name: 'pushgateway'
  scrape_interval: 15s
  honor_labels: true
  scheme: http
  static_configs:
  - targets: ['pushgateway:9091']
